[project]
name = "backend"
version = "0.1.0"
description = "Application Tracker API"
readme = "README.md"
authors = [
    { name = "Joseph MV", email = "josephmv43@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "sqlalchemy>=2.0.0",
    "alembic>=1.13.0",
    "psycopg[binary]",
    "pydantic-settings",
]

[project.scripts]
backend = "app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""
