"""create job_posts

Revision ID: a749a27aa907
Revises: 186ea778f1f4
Create Date: 2026-09-16 07:03:48.462034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a749a27aa907'
down_revision: Union[str, Sequence[str], None] = '186ea778f1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_summary', sa.Text(), nullable=True),
    sa.Column('posting_url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', 'temporary', 'freelance', name='employmenttype'), nullable=True),
    sa.Column('experience_level', sa.Enum('intern', 'entry', 'mid', 'senior', 'staff', 'principal', 'executive', name='experiencelevel'), nullable=True),
    sa.Column('remote_type', sa.Enum('on_site', 'remote', 'hybrid', name='remotetype'), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posting_status', sa.Enum('active', 'expired', 'filled', 'removed', 'unknown', name='postingstatus'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', name='uq_job_posts_url_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posts')
    # ### end Alembic commands ###
