"""create companies

Revision ID: fc167b3f5c9e
Revises: 
Create Date: 2026-08-23 10:56:56.831955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc167b3f5c9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('career_page_url', sa.String(length=2048), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('company_type', sa.Enum('product', 'service', 'hybrid', name='companytype'), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('headquarters_location', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
